/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _NODE_H_RPCGEN
#define _NODE_H_RPCGEN

#include <rpc/rpc.h>

extern char * tracker_host;

#ifdef __cplusplus
extern "C" {
#endif

#define MAXHOSTNAME 32
#define MAXFILELEN 65535
#define MAXNAMELEN 255

struct file_rqst_data {
	char *filename;
	int file_position;
	int chunk_size;
};
typedef struct file_rqst_data file_rqst_data;

struct file {
	char *filename;
	char *file_contents;
	int caller;
	int file_size;
	struct file *next;
};
typedef struct file file;

#define NODE_PROG 0x20000001
#define NODE_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define STORE_NEW_FILE 1
extern  int * store_new_file_1(file *, CLIENT *);
extern  int * store_new_file_1_svc(file *, struct svc_req *);
#define TRANSFER_FILE 2
extern  char ** transfer_file_1(file_rqst_data *, CLIENT *);
extern  char ** transfer_file_1_svc(file_rqst_data *, struct svc_req *);
extern int node_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define STORE_NEW_FILE 1
extern  int * store_new_file_1();
extern  int * store_new_file_1_svc();
#define TRANSFER_FILE 2
extern  char ** transfer_file_1();
extern  char ** transfer_file_1_svc();
extern int node_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_file_rqst_data (XDR *, file_rqst_data*);
extern  bool_t xdr_file (XDR *, file*);

#else /* K&R C */
extern bool_t xdr_file_rqst_data ();
extern bool_t xdr_file ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_NODE_H_RPCGEN */
