/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TORRENT_STORE_H_RPCGEN
#define _TORRENT_STORE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXHOSTNAME 32
#define MAXFILELEN 65535
#define MAXNAMELEN 255

struct torrent_file {
	char *filename;
	struct torrent_file *next;
};
typedef struct torrent_file torrent_file;

#define TORRENT_STORE_PROG 0x20000002
#define TORRENT_STORE_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define LOCATE_TRACKER 1
extern  char ** locate_tracker_1(void *, CLIENT *);
extern  char ** locate_tracker_1_svc(void *, struct svc_req *);
#define CREATE_TORRENT 2
extern  int * create_torrent_1(char **, CLIENT *);
extern  int * create_torrent_1_svc(char **, struct svc_req *);
#define QUERY_FILE 3
extern  char ** query_file_1(char **, CLIENT *);
extern  char ** query_file_1_svc(char **, struct svc_req *);
#define TRACKER_REGISTER 4
extern  int * tracker_register_1(char **, CLIENT *);
extern  int * tracker_register_1_svc(char **, struct svc_req *);
extern int torrent_store_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define LOCATE_TRACKER 1
extern  char ** locate_tracker_1();
extern  char ** locate_tracker_1_svc();
#define CREATE_TORRENT 2
extern  int * create_torrent_1();
extern  int * create_torrent_1_svc();
#define QUERY_FILE 3
extern  char ** query_file_1();
extern  char ** query_file_1_svc();
#define TRACKER_REGISTER 4
extern  int * tracker_register_1();
extern  int * tracker_register_1_svc();
extern int torrent_store_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_torrent_file (XDR *, torrent_file*);

#else /* K&R C */
extern bool_t xdr_torrent_file ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TORRENT_STORE_H_RPCGEN */
